{% set name = "aiohttp-debugtoolbar" %}
{% set version = "0.6.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ec231661133b40136608d39dfb688e7ea0c3d47b6ae6dee52d5bf24ceb9e4d45

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - aiohttp >=2.0.7
    - aiohttp-jinja2
    - pip
    - python >3
  run:
    - aiohttp >=2.0.7
    - aiohttp-jinja2
    - python >3

test:
  imports:
    - aiohttp_debugtoolbar
    - aiohttp_debugtoolbar.panels
    - aiohttp_debugtoolbar.tbtools

about:
  home: https://github.com/aio-libs/aiohttp-debugtoolbar
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: debugtoolbar for aiohttp

extra:
  recipe-maintainers:
    - epruesse
