travis:
  secure:
    BINSTAR_TOKEN: QJ4H/4cNYgWHuDK2FZdbg2qc9Vlo39osFjfQUbEpy6D1XuMoyeSY7Drxn2dDPKq8nunTFe5Pzdynik+wDVTPHRzkKjgWqYHz1UANVGUXVFRSG6kkSnqVzvMnf1RPRvdR7i9EvLdu/CpkoQfPBk7i3KCoGdkBrdnd64JxCM5FctI5r/9iM/BI7m9TrhY54spZRVdsxyc21y439m3Kj+gyJbHqRpiLdjkB+ynTUL++rL0z8hlhj/yJV3uKLnDdFL2Aso2TsoJ2FrnyNCTZaIp2S/WjAzB+PC2Daf20BfyZF3J9I2KJ1hRbyUovFtDN9/9JG04w87Zlz4+elaghOoA5Rw0Sx+ouyfcWhdgBEmZf5BJ23MiTP5wxGiX8jdCShFM8VLho6VNkX9FC7lHh0iXECXz5j83zXsA+rR8V7QCI9UcsKpobXw67k4oN+aXD96PwMg9f+e2xXwWx3eRQ5OHAxPxD01mQ37/Fx6Fl1QIfU1HfdJnxzldsT9liDEAGAJUTRvIrzTbxLG9Hk7TM2vLngR0IXFJHbwQf27umwymTkim36qjtmuREkpNno/3JDY6AYbmvmKMOrg3iXeKyuS9sPHXdiI4/GSkN6HwkjI3JeWvNp6XX3pd5ab8xtruhq+ODfGuxuFmEnT3yv2Zksj4u9Vbf8fvL+703PN0pusr0xy8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
